apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" .Values.db.user .Values.db.password .Values.db.host .Values.db.port .Values.db.name | b64enc | quote }}
