apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" . }}
  labels:
  {{- include "users.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "users.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.http.port }}
      name: web
      protocol: TCP
  type: {{ .Values.service.type }}
